In [1]:
import pandas as  pd

In [2]:
df = pd.read_csv('deta.csv')
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [3]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False